### PR TITLE
cs50/2018/x/scratch

### PR DESCRIPTION
**Pull request by itsmylove0810**
https://scratch.mit.edu/projects/196793572/

### CODE REVIEW

**Comment by alaakadry** [comment]
https://scratch.mit.edu/projects/210817444/

**Comment by hakangon** [comment]
https://scratch.mit.edu/projects/225696489/

**Comment by dianasakura** [comment]
https://scratch.mit.edu/projects/230363149/

**Comment by crossroads1112** [comment]
Hey @itsmylove0810  @alaakadry  @ghost @dianasakura,

You to submit pset0 please follow the instructions [here](https://docs.cs50.net/2018/x/psets/0/pset0.html#how-to-submit). Importantly, note the instruction that says

> Go to https://github.com/submit50/USERNAME, replacing USERNAME with your own GitHub username.

You should replace USERNAME with your own username, so @itsmylove0810 would go to https://github.com/submit50/itsmylove0810, @alaakadry would go to https://github.com/submit50/alaakadry etc.

**Pull request closed without merging**
